import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sfProDisplay = localFont({
  src: "./fonts/SFProDisplayRegular.otf",
  variable: "--font-sf-pro-display",
  weight: "400", 
});
const sfProDisplayMedium = localFont({
  src: "./fonts/SFProDisplayMedium.otf",
  variable: "--font-sf-pro-display",
  weight: "400", 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfProDisplay.variable} ${sfProDisplayMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
